kubectl delete ephemeral resources on destroy
This took a bit of work, as on destroy the template_dir resources
are not rendered, so we can't call
*kubectl delete -f rendered_ephemeral_folder*
I explored *depends_on* but that didn't work either.

depends_on = [
  template_dir.ephemeral
]

In the end I explored provisioner found the terraform.tfstate which we
can query with jq to retrieve the owner (nampsace) and the spacename in
order to selectively delete our ephemeral resources.

==> ⧗ Detecting persistent resources
There are some problems with the configuration, described below.
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
Error: Invalid reference from destroy provisioner
  on namedspaced.tf line 97, in resource "null_resource" "namespace":
  97:   depends_on = [
  98:     template_dir.ephemeral
  99:   ]
Destroy-time provisioners and their connection configurations may only
reference attributes of the related resource, via 'self', 'count.index', or
'each.key'.
References to other resources during the destroy phase can cause dependency
cycles and interact poorly with create_before_destroy.
==> ⧗ Detecting persistent resources
Terraform 1.5.3
Error: Unsupported argument
on namedspaced.tf line 71, in resource "null_resource" "namespace":
  71:   depends_on = [
An argument named "depends_on" is not expected here.