Ensure template dirs exist before kubectl run
We are speeding things up by calling kubectl directly
on template_dir.persistent and template_dir.ephemeral.

When we destroy (kubectl delete -f) the ephemeral resources,
we need to ensure the template_dir exist... otherwise we get the
following error:

 Error: local-exec provisioner error
 on namedspaced.tf line 90, in resource "null_resource" "namespace":
   90: provisioner "local-exec" {

 Error running command '../../kubectl delete -f ephemeral': exit status 1. Output: error: the path "ephemeral" does not exist